##########################################################################
# Title:         Community: vnstat | Default Variables                   #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Community                   #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

vnstat_name: speedtest

################################
# Web
################################

vnstat_web_subdomain: "{{ vnstat_name }}"
vnstat_web_domain: "{{ user.domain }}"
vnstat_web_port: "80"
vnstat_web_url: "{{ 'https://' + vnstat_web_subdomain + '.' + vnstat_web_domain
                    if (reverse_proxy_is_enabled)
                    else 'http://localhost:' + vnstat_web_port }}"

################################
# DNS
################################

vnstat_dns_record: "{{ vnstat_web_subdomain }}"
vnstat_dns_zone: "{{ vnstat_web_domain }}"

################################
# Traefik
################################

vnstat_traefik_middleware: "secureHeaders@file,gzip,vnstat-auth"
vnstat_traefik_certresolver: "{{ traefik_default_certresolver }}"
vnstat_traefik_enabled: true
vnstat_auth: "/etc/traefik/auth"

################################
# Docker
################################

# Container
vnstat_docker_container: "{{ vnstat_name }}"

# Image
vnstat_docker_image_pull: true
vnstat_docker_image_tag: "latest"
vnstat_docker_image: "amarston/vnstat-dashboard:{{ vnstat_docker_image_tag }}"

# Ports
vnstat_docker_ports_defaults:
  - "{{ vnstat_web_port }}:{{ vnstat_web_port }}"
vnstat_docker_ports_custom: []
vnstat_docker_ports: "{{ vnstat_docker_ports_defaults
                         + vnstat_docker_ports_custom
                      if (not reverse_proxy_is_enabled)
                      else [] + vnstat_docker_ports_custom }}"

# Envs
vnstat_docker_envs_default:
  TZ: "{{ tz }}"
vnstat_docker_envs_custom: {}
vnstat_docker_envs: "{{ vnstat_docker_envs_default
                        | combine(vnstat_docker_envs_custom) }}"

# Commands
vnstat_docker_commands_default: []
vnstat_docker_commands_custom: []
vnstat_docker_commands: "{{ vnstat_docker_commands_default
                            + vnstat_docker_commands_custom}}"

# Volumes
vnstat_docker_volumes_default:
  - "/usr/bin/vnstat:/usr/bin/vnstat:ro"
  - "/var/lib/vnstat:/var/lib/vnstat:ro"
vnstat_docker_volumes_custom: []
vnstat_docker_volumes: "{{ vnstat_docker_volumes_default
                           + vnstat_docker_volumes_custom
                           + docker_volumes_downloads_common }}"

# Devices
vnstat_docker_devices_default: []
vnstat_docker_devices_custom: []
vnstat_docker_devices: "{{ vnstat_docker_devices_default
                           + vnstat_docker_devices_custom }}"

# Hosts
vnstat_docker_hosts_default: []
vnstat_docker_hosts_custom: []
vnstat_docker_hosts: "{{ docker_hosts_common
                         | combine(vnstat_docker_hosts_default)
                         | combine(vnstat_docker_hosts_custom) }}"

# Labels
vnstat_docker_labels_default:
  traefik.http.middlewares.vnstat-auth.basicauth.usersfile: "{{ vnstat_auth }}"
vnstat_docker_labels_custom: {}
vnstat_docker_labels: "{{ docker_labels_common
                          | combine(vnstat_docker_labels_default)
                          | combine(vnstat_docker_labels_custom) }}"

# Hostname
vnstat_docker_hostname: "{{ vnstat_name }}"

# Networks
vnstat_docker_networks_alias: "{{ vnstat_name }}"
vnstat_docker_networks_default: []
vnstat_docker_networks_custom: []
vnstat_docker_networks: "{{ docker_networks_common
                            + vnstat_docker_networks_default
                            + vnstat_docker_networks_custom }}"

# Capabilities
vnstat_docker_capabilities_default: []
vnstat_docker_capabilities_custom: []
vnstat_docker_capabilities: "{{ vnstat_docker_capabilities_default
                                + vnstat_docker_capabilities_custom }}"

# Security Opts
vnstat_docker_security_opts_default: []
vnstat_docker_security_opts_custom: []
vnstat_docker_security_opts: "{{ vnstat_docker_security_opts_default
                                 + vnstat_docker_security_opts_custom }}"

# Restart Policy
vnstat_docker_restart_policy: unless-stopped

# State
vnstat_docker_state: started
