#########################################################################
# Title:         Community: Sanity Check | Logs                         #
# Author(s):     desimaniac, kowalski                                   #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Logs | Get '{{ sanity_check_logs_playbook_path | basename }}' info
  stat:
    path: "{{ sanity_check_logs_playbook_path }}"
  register: community_yml

- name: Logs | Touch '{{ sanity_check_logs_logfile_path | basename }}'
  file:
    path: "{{ sanity_check_logs_logfile_path }}"
    state: touch
    owner: "{{ community_yml.stat.uid }}"
    group: "{{ community_yml.stat.gid }}"
    mode: 0664
