#########################################################################
# Title:         Community: Sanity Check | Ansible Version              #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Import Default Sanity Check variables
  include_vars: /srv/git/saltbox/roles/sanity_check/defaults/main.yml

- name: Find Ansible version
  shell: python3 -c 'from ansible_collections.ansible_release import ansible_version; print(ansible_version)'
  register: registered_ansible_version

- name: Print Ansible version
  debug:
    msg:
      - "Installed Ansible version: {{ registered_ansible_version.stdout }}."
      - "Installed Ansible Core version: {{ ansible_version.full }}."

- name: Check if Ansible needs upgrading
  set_fact:
    ansible_update: true
  when: registered_ansible_version.stdout is version(sanity_check_ansible_version_min, 'lt', version_type='semver')

- name: Upgrade Ansible
  script:
    cmd: /srv/git/saltbox/scripts/update.sh
  become: true
  become_user: root
  when: ansible_update

- name: "Upgrade Ansible | Check if Ansible was upgraded"
  block:
    - name: "Upgrade Ansible | Print Instructions"
      debug:
        msg:
          - "Ansible was upgraded"
          - "You will need to re-run your previous tag."

    - name: "Upgrade Ansible | Exit"
      meta: end_play
  when: ansible_update
