#########################################################################
# Title:            Community: InfluxDB Role                            #
# Author(s):        desimaniac                                          #
# URL:              https://github.com/saltyorg/Community               #
# Docker Image(s):  influxdb                                            #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing containers
  docker_container:
    name: influxdb
    state: absent

- name: Create required directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/influxdb

- name: Create and start influxdb container
  docker_container:
    name: influxdb
    image: "influxdb:1.8.4"
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/influxdb:/var/lib/influxdb"
    labels:
      "com.github.saltbox.saltbox_managed": "true"
    networks:
      - name: saltbox
        aliases:
          - influxdb
    purge_networks: true
    restart_policy: unless-stopped
    state: started
