---
- hosts: localhost
  vars_files:
    - ['settings.yml', 'defaults/settings.yml.default']
    - ['/srv/git/saltbox/accounts.yml', '/srv/git/saltbox/defaults/accounts.yml.default']
    - ['/srv/git/saltbox/settings.yml', '/srv/git/saltbox/defaults/settings.yml.default']
    - ['/srv/git/saltbox/adv_settings.yml', '/srv/git/saltbox/defaults/adv_settings.yml.default']
  roles:
    # Reqs
    - { role: settings, tags: ['settings'] }
    - { role: sanity_check, tags: ['always', 'sanity_check'] }
    - { role: pre_tasks, tags: ['pre_tasks'] }
    # Apps
    - { role: bazarr, tags: ['bazarr'] }
    - { role: bazarrx, tags: ['bazarrx'] }
    - { role: deluge, tags: ['deluge'] }
    - { role: delugex, tags: ['delugex'] }
    - { role: hetzner_nfs, tags: ['hetzner_nfs_server', 'hetzner_nfs_server_uninstall', 'hetzner_nfs_client_mount', 'hetzner_nfs_client_unmount'] }
    - { role: overseerrx, tags: ['overseerrx'] }
    - { role: qbittorrent, tags: ['qbittorrent'] }
    - { role: qbittorrentx, tags: ['qbittorrentx'] }
    - { role: readarr, tags: ['readarr'] }
    - { role: readarrx, tags: ['readarrx'] }
    - { role: sonarrx, tags: ['sonarrx'] }
