#########################################################################
# Title:            Community: qbittorrentX                             #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Community               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute qbittorrentX roles"
  include_role:
    name: qbittorrent
  vars:
    qbittorrent_name: "qbittorrent{{ role }}"
  with_items: "{{ qbittorrentx.roles }}"
  loop_control:
    loop_var: role
