#########################################################################
# Title:         Community: Plex Meta Manager                           #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent
    container_default_behavior: compatibility

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Download config.yml.template
  get_url:
    url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template
    dest: "{{ plex_meta_manager_paths_location }}/config/config.yml.template"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes
    validate_certs: no
  ignore_errors: yes

- name: "Look for 'config.yml' file in plex-meta-manager/config folder"
  stat:
    path: "{{ plex_meta_manager_paths_location }}/config/config.yml"
  register: meta_config

- name: "Fail when 'config.yml' is not present"
  fail:
    msg: "You need to setup your config file. https://github.com/meisnate12/Plex-Meta-Manager/wiki/Configuration-File"
  when: (not meta_config.stat.exists) and (not continuous_integration)

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Alert user to make and verify the config and auth.
  debug:
      msg:
        - "You should attempt a manual run first to ensure the config is working and to use oAuth for Trakt config etc. To do this run the below command"
        - "docker run --rm -it -v {{ plex_meta_manager_paths_location }}/config:/config {{ plex_meta_manager_docker_image }} --run"
