#########################################################################
# Title:            Community: Apprise                                  #
# Author(s):        owine, kowalski                                     #
# URL:              https://github.com/saltyorg/Community               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Create auth file
  community.general.htpasswd:
    path: /opt/traefik/auth
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
  no_log: true

  # - name: Create htpasswd
  # htpasswd:
  #   path: "/opt/nginx-proxy/htpasswd/{{ item }}.{{ user.domain }}"
  #   name: "{{ user.name }}"
  #   password: "{{ user.pass }}"
  #   owner: "{{ user.name }}"
  #   group: "{{ user.name }}"
  #   mode: 0664
  # with_items:
  #   - apprise
