#########################################################################
# Title:            Community: Calibre-Web                              #
# Author(s):        Superduper09, -SK, kowalski                         #
# URL:              https://github.com/saltyorg/Community               #
# Docker Image(s):  linuxserver/calibre-web                             #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

calibre_web_name: calibre-web

################################
# Paths
################################

calibre_web_paths_folder: "{{ calibre_web_name }}"
calibre_web_paths_location: "{{ server_appdata_path }}/{{ calibre_web_paths_folder }}"
calibre_web_paths_folders_list:
  - "{{ calibre_web_paths_location }}"

################################
# Web
################################

calibre_web_web_subdomain: "{{ calibre_web_name }}"
calibre_web_web_domain: "{{ user.domain }}"
calibre_web_web_port: "8083"
calibre_web_web_url: "{{ 'https://' + calibre_web_web_subdomain + '.' + calibre_web_web_domain
                      if (reverse_proxy_is_enabled)
                      else 'http://localhost:' + calibre_web_web_port }}"

################################
# DNS
################################

calibre_web_dns_record: "{{ calibre_web_web_subdomain }}"
calibre_web_dns_zone: "{{ calibre_web_web_domain }}"

################################
# Traefik
################################

calibre_web_traefik_middleware: "secureHeaders@file,gzip"
calibre_web_traefik_certresolver: "{{ traefik_default_certresolver }}"
calibre_web_traefik_enabled: true

################################
# Docker
################################

# Container
calibre_web_docker_container: "{{ calibre_web_name }}"

# Image
calibre_web_docker_image_pull: true
calibre_web_docker_image_tag: "latest"
calibre_web_docker_image: "ghcr.io/linuxserver/calibre-web:{{ calibre_web_docker_image_tag }}"

# Ports
calibre_web_docker_ports_defaults:
  - "{{ calibre_web_web_port }}"
calibre_web_docker_ports_custom: []
calibre_web_docker_ports: "{{ calibre_web_docker_ports_defaults
                              + calibre_web_docker_ports_custom
                           if (not reverse_proxy_is_enabled)
                           else [] + calibre_web_docker_ports_custom }}"

# Envs
calibre_web_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  USE_CONFIG_DIR: "true"
  DOCKER_MODS: linuxserver/calibre-web:calibre
calibre_web_docker_envs_custom: {}
calibre_web_docker_envs: "{{ calibre_web_docker_envs_default
                             | combine(calibre_web_docker_envs_custom) }}"

# Commands
calibre_web_docker_commands_default: []
calibre_web_docker_commands_custom: []
calibre_web_docker_commands: "{{ calibre_web_docker_commands_default
                                 + calibre_web_docker_commands_custom }}"

# Volumes
calibre_web_docker_volumes_default:
  - "{{ calibre_web_paths_location }}:/calibre-web"
  - "{{ calibre_web_paths_location }}/config:/config"
  - "/mnt/unionfs/Media/Books:/books"
  - "/mnt:/mnt"
calibre_web_docker_volumes_custom: []
calibre_web_docker_volumes: "{{ calibre_web_docker_volumes_default
                                + calibre_web_docker_volumes_custom
                                + docker_volumes_downloads_common }}"

# Devices
calibre_web_docker_devices_default: []
calibre_web_docker_devices_custom: []
calibre_web_docker_devices: "{{ calibre_web_docker_devices_default
                                + calibre_web_docker_devices_custom }}"

# Hosts
calibre_web_docker_hosts_default: []
calibre_web_docker_hosts_custom: []
calibre_web_docker_hosts: "{{ docker_hosts_common
                              | combine(calibre_web_docker_hosts_default)
                              | combine(calibre_web_docker_hosts_custom) }}"

# Labels
calibre_web_docker_labels_default: {}
calibre_web_docker_labels_custom: {}
calibre_web_docker_labels: "{{ docker_labels_common
                               | combine(calibre_web_docker_labels_default)
                               | combine(calibre_web_docker_labels_custom) }}"

# Hostname
calibre_web_docker_hostname: "{{ calibre_web_name }}"

# Networks
calibre_web_docker_networks_alias: "{{ calibre_web_name }}"
calibre_web_docker_networks_default: []
calibre_web_docker_networks_custom: []
calibre_web_docker_networks: "{{ docker_networks_common
                                 + calibre_web_docker_networks_default
                                 + calibre_web_docker_networks_custom }}"

# Capabilities
calibre_web_docker_capabilities_default: []
calibre_web_docker_capabilities_custom: []
calibre_web_docker_capabilities: "{{ calibre_web_docker_capabilities_default
                                     + calibre_web_docker_capabilities_custom }}"

# Security Opts
calibre_web_docker_security_opts_default: []
calibre_web_docker_security_opts_custom: []
calibre_web_docker_security_opts: "{{ calibre_web_docker_security_opts_default
                                      + calibre_web_docker_security_opts_custom }}"

# Restart Policy
calibre_web_docker_restart_policy: unless-stopped

# State
calibre_web_docker_state: started
