#########################################################################
# Title:            Community: Sshwifty                                 #
# Author(s):        astromd, kowalski                                   #
# URL:              https://github.com/saltyorg/Community               #
# Docker Image(s):  niruix/sshwifty                                     #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Settings | Check if `{{ sshwifty_paths_config_location | basename }}` exists
  stat:
    path: "{{ sshwifty_paths_config_location }}"
  register: sshwifty_config

- name: Settings | New `{{ sshwifty_paths_config_location | basename }}` tasks
  block:

  - name: Settings | Import default `{{ sshwifty_paths_config_location | basename }}`
    template:
      src: sshwifty.conf.json.j2
      dest: "{{ sshwifty_paths_config_location }}"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: 0775

  when: not sshwifty_config.stat.exists
