#########################################################################
# Title:            Community: BazarrX                                  #
# Author(s):        Migz93, salty                                       #
# URL:              https://github.com/saltyorg/Community               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute BazarrX roles"
  include_role:
    name: bazarr
  vars:
    bazarr_name: "bazarr{{ role }}"
  with_items: "{{ bazarrx.roles }}"
  loop_control:
    loop_var: role
