#########################################################################
# Title:            Community: SonarrX                                  #
# Author(s):        Kalroth, Migz93, salty                              #
# URL:              https://github.com/saltyorg/Community               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute SonarrX roles"
  include_role:
    name: sonarr
  vars:
    sonarr_name: "sonarr{{ role }}"
  with_items: "{{ sonarrx.roles }}"
  loop_control:
    loop_var: role
