#########################################################################
# Title:         Community: Pre-Tasks Role                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: APT Tasks
  import_tasks: "subtasks/apt.yml"
  tags: always
