#########################################################################
# Title:            Community: alternatrr                               #
# Author(s):        TheUltimateC0der, salty                             #
# URL:              https://github.com/saltyorg/Community               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute alternatrrX roles"
  include_role:
    name: alternatrr
  vars:
    alternatrr_name: "alternatrr{{ role }}"
    sonarr_name: "sonarr{{ role }}"
  with_items: "{{ alternatrrx.roles }}"
  loop_control:
    loop_var: role
