#########################################################################
# Title:            Community: rfloodX                                  #
# Author(s):        salty                                               #
# URL:              https://github.com/saltyorg/Community               #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute rfloodX roles"
  include_role:
    name: rflood
  vars:
    rflood_name: "rflood{{ role }}"
  with_items: "{{ rfloodx.roles }}"
  loop_control:
    loop_var: role
