#########################################################################
# Title:         Community: Settings | Ansible Config                   #
# Author(s):     l3uddz, desimaniac, Migz93, salty                      #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Settings Role updated 'ansible.cfg'."
  debug:
    msg:
      - "Settings Role updated 'ansible.cfg'"
      - "You will need to re-run your previous tag to continue."

- name: "Exit so that user can check updated config files"
  debug:
    msg: "Community Installer will now exit."

- name: "Exit"
  meta: end_play
