#########################################################################
# Title:         Community: Settings | Ansible Config                   #
# Author(s):     l3uddz, desimaniac, Migz93, salty                      #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Settings Role updated 'ansible.cfg'."
  debug:
    msg:
      - "Settings Role updated 'ansible.cfg'"
      - "You will need to re-run your previous tag to continue."

- name: Set 'exit_is_necessary' variable
  set_fact:
    exit_is_necessary: true
