#########################################################################
# Title:         Community: Settings | Migrator                         #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Migrator | Migrations for all config files
  block:

    - name: Migrator | All | Migration 01
      include_tasks: "migrator/all/migration_01.yml"
      when: (file != "backup_config.yml")

  when: (file != "ansible.cfg")

- name: Migrator | Migrations for 'ansible.cfg'
  block:

    - name: Migrator | 'ansible.cfg' | Migration 01
      include_tasks: "migrator/ansible_cfg/migration_01.yml"

  when: (file == "ansible.cfg")
