#########################################################################
# Title:         Community: Settings | Re-encrypt                       #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Community                  #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Re-encrypt | Re-encrypt '{{ file }}' if previously encrypted"
  shell: "ansible-vault encrypt {{ playbook_dir }}/{{ file }}"
  become: true
  become_user: "{{ community_yml.stat.pw_name }}"
  when: file_is_encrypted
