#########################################################################
# Title:         Community: AirDC++ Role                                #
# Author(s):     l3uddz, salty                                          #
# URL:           https://github.com/saltyorg/Community                  #
# Docker Image:  gangefors/airdcpp-webclient                            #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent
    container_default_behavior: compatibility

- name: Create directories
  file: "path={{ item }} state=directory owner={{ user.name }} group={{ user.name }} mode=0775"
  with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: Check WebServer.xml exists
  stat:
    path: "/opt/airdcpp/WebServer.xml"
  register: webserver_xml

- name: Check DCPlusPlus.xml exists
  stat:
    path: "/opt/airdcpp/DCPlusPlus.xml"
  register: dcplusplus_xml

- name: Import default 'WebServer.xml'
  copy:
    src: WebServer.xml
    dest: /opt/airdcpp/WebServer.xml
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: true
  when: not webserver_xml.stat.exists

- name: Import default 'DCPlusPlus.xml'
  copy:
    src: DCPlusPlus.xml
    dest: /opt/airdcpp/DCPlusPlus.xml
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: true
  when: not dcplusplus_xml.stat.exists

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
