name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  install:
    name: '${{ matrix.roles }}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        roles:
          - gitea
          - airdcpp 
          - airsonic 
          - alltube 
          - alternatrr 
          - alternatrrx 
          - asshama 
          - autoscan 
          - deluge 
          - grafana 
          - influxdb 
          - lidarrx 
          - ombi 
          - ombix 
          - prowlarr 
          - qbittorrent 
          - radarrx 
          - sonarrx 
          - speedtest 
          - transfer 
          - transmission
      fail-fast: false

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: curl https://raw.githubusercontent.com/saltyorg/sb/master/sb_install.sh --output sb_install.sh && sudo bash sb_install.sh -v

      - name: Chown /srv/git
        run: sudo chown -R runner:runner /srv/git

      - name: Remove accounts.yml
        run: cd /srv/git/saltbox && rm -rf accounts.yml

      - name: Download Github Actions accounts.yml
        run: cd /srv/git/saltbox && curl -o accounts.yml https://raw.githubusercontent.com/saltydk/AppveyorTest/main/github.yml

      - name: Create, chown and chmod /tmp/ansible
        run: sudo mkdir /tmp/ansible && sudo chown -R runner:runner /tmp/ansible && chmod 0777 /tmp/ansible

      - name: Syntax Check
        run: cd /srv/git/saltbox && sudo ansible-playbook saltbox.yml --syntax-check

      - name: Install Saltbox
        run: cd /srv/git/saltbox && sudo ansible-playbook saltbox.yml --tags "core" --skip-tags "sanity_check,settings,kernel,hetzner,shell,rclone,system,motd,nvidia,mounts,scripts" --extra-vars '{"continuous_integration":true}'

      - name: Copy default configuration
        run: cp -n defaults/ansible.cfg.default ansible.cfg && cp -n defaults/settings.yml.default settings.yml

      - name: Install ${{ matrix.roles }}
        run: sudo ansible-playbook community.yml --tags "${{ matrix.roles }}" --skip-tags "sanity_check,settings" --extra-vars '{"continuous_integration":true}'

### Need to fix webhook reporting success even if there is a failure in the matrix
  webhook:
    name: '${{ matrix.roles }}'
    runs-on: ubuntu-20.04
    needs: install
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
          status: ${{ env.WORKFLOW_CONCLUSION }}
