####################################################################################
# Title:         Community: qBittorrent | Post-Install | Settings                  #
# Author(s):     salty                                                             #
# URL:           https://github.com/saltyorg/Community                             #
# --                                                                               #
####################################################################################
#                   GNU General Public License v3.0                                #
####################################################################################
---
- name: Post-Install | Settings | Update 'qBittorrent.conf' config settings
  ini_file:
    path: "{{ qbittorrent_paths_conf }}"
    section: Preferences
    option: Connection\PortRangeMin
    value: "{{ qbittorrent_docker_ports_56881 }}"
    no_extra_spaces: true
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0775"
